print("creating a string:")
s="goodmorning"
print(s)
print("indexing:")
print(s[1])
print(s[0])
print(s[6])
print("slicing:")
print(s[2:])
print(s[7:])
print(s[:4])
print("concatenation:")
print(s+" prathiba")
print(s+" have ur coffee")
S=s+" prathiba"
print(S)
print("repetition:")
print(s*2)
print(S*2)
print("membership operator:(in/not in):")
s="good morning"
print("m"in s)
print("a"not in s)
